### ISSUE TITLE
Enabling MQTT on Buildroot

### ISSUE THREAD

**Issue by kevintom98** [cu-ecen-aeld/final-project-dhirajbennadi#5]
Add Support for enabling MQTT Protocol on Raspberry Pi booted with buildroot.

Definition of Done:
1. Be able to invoke MQTT Library Files on Rapsberry Pi application.
2. Will be able to publish or subscribe to a topic (this can only be done if application layer code is working).

Blocker:
Support for MQTT on Buildroot (We are planning to use [Mosquitto](https://mosquitto.org/))

**Comment by kevintom98** [comment]
Wifi connection is now enabled on Buildroot, wifi is automatically connected on start now. This took some time to debug as there were incomplete steps mentioned in the Wifi-Config Wiki page for Raspberry Pi. Found the complete steps and we could write a better tutorial for this.

[Wifi automation scripts](https://github.com/cu-ecen-aeld/final-project-kevintom98/commit/9038050b4aed9d14617f0e781db76619c0625d4c)
![Wifi_working](https://user-images.githubusercontent.com/15712385/202963122-5cbf4619-31d7-4595-aac1-3755bb93b582.jpg)

**Comment by kevintom98** [comment]
MOSQUITTO was enabled and installed. The image which has MOSQUITTO have been generated and tested on RPi.
[MOSQUITTO ENABLED](https://github.com/cu-ecen-aeld/final-project-kevintom98/commit/42e334802c12640f93350f7013bce747b23dd090)

**Comment by kevintom98** [comment]
HIVEMQ account created and enabled MOSQUITTO configurations

**Comment by kevintom98** [comment]
![MQTT](https://user-images.githubusercontent.com/15712385/202978586-460d6493-0069-4878-8bf5-67e165366244.jpg)

Mosquitto enabled for local communication

**Comment by dhirajbennadi** [comment]
Reviewed by @dhirajbennadi
