### ISSUE TITLE
Application Code to Connect to MQTT Broker and UART Interfacing - Buildroot

### ISSUE THREAD

**Issue by dhirajbennadi** [cu-ecen-aeld/final-project-dhirajbennadi#7]

**Comment by dhirajbennadi** [comment]
Sprint 3 focusses on interfacing UART on Rpi and MQTT Support on Buildroot

DOD:
Be able to establish a communication between the UART Sensor and Rpi
Be able to establish a communication between the Rpi and MQTT Broker

Blocker:
UART userspace driver intergration

**Comment by kevintom98** [comment]
Implemented MQTT communication from Raspberry Pi to local Ubuntu system over Wifi

[MQTT Working Over HIVEMQ](https://github.com/cu-ecen-aeld/final-project-kevintom98/commit/d04b1f2b4fbb5ea106b5de32b66330928e17605)

**PUBLISHER**
![IMG-7913](https://user-images.githubusercontent.com/15712385/205169659-04b6a9f3-8c4e-4fd6-aab2-5fe25c7a500a.jpg)


**SUBSCRIBER**
![Screenshot_from_2022-12-01_15-03-42](https://user-images.githubusercontent.com/15712385/205169761-7a463716-9861-4955-93e3-2a7a90b7c52e.png)

**Comment by kevintom98** [comment]
**Application Code Links**
[Most recent commit](https://github.com/kevintom98/AESD_App_Code/commit/cc24118b52bf34619c13eee1405e0a4af2cec98f)
[Buildroot Application Code](https://github.com/kevintom98/AESD_App_Code)

**Comment by kevintom98** [comment]
UART communication and MQTT upload successful. 
![unnamed](https://user-images.githubusercontent.com/15712385/205530223-8ec4d59e-769e-4213-b0bb-e834963ac2a7.jpg)

**Comment by kevintom98** [comment]
**Commit Links**
[Application Code](https://github.com/kevintom98/AESD_App_Code/tree/main/src)
[Buildroot Repo](https://github.com/cu-ecen-aeld/final-project-kevintom98/commit/13d95751076f19a790e15654b847af174dee4603)

Blocking Resolved : [UART Interface Code](https://github.com/kevintom98/AESD_App_Code/blob/main/src/UART.c)
